Controllers/ArchivosController.cs
using Ionic.Zip;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ClientesProspectos.Controllers
{
    public class ArchivosController : Controller
    {

        public IActionResult Index()
        {

            return View();

        }

        [HttpPost("FileUpload")]
        public async Task<IActionResult> FileUpload(List<IFormFile> files, string usuario)
        {
            var NombreCarpeta = usuario;

            var size = files.Sum(f => f.Length);
            var filePaths = new List<string>();

            foreach (var formfile in files)
            {
                if (formfile.Length > 0)
                {
                    var newfolder = Directory.GetCurrentDirectory() + "/wwwroot/Archivos/"+ NombreCarpeta;

                    Directory.CreateDirectory(newfolder);

                    var filePath = Path.Combine(newfolder, formfile.FileName);
                    filePaths.Add(filePath);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await formfile.CopyToAsync(stream);
                    }
                }
            }
            return Redirect("/home/Listado");
            //return null;
        }



        //[HttpPost("FileDownload")]
        //public List<string> FileDownload(string usuario)
        //{
        //    var NombreCarpeta = usuario;             

        //    var Ruta = Directory.GetCurrentDirectory() + "/wwwroot/Archivos/" + NombreCarpeta;
        //    var dir = new System.IO.DirectoryInfo(Server.MapPath(""));
        //    System.IO.FileInfo[] fileNames = dir.GetFiles("*.*");
        //}


        [HttpPost("FileDownload")]
        public FileResult FileDownload(string usuario)
        {
            var NombreCarpeta = usuario;             

            var Ruta = Directory.GetCurrentDirectory() + "/wwwroot/Archivos/" + NombreCarpeta;

            //var Archivo = System.IO.File.ReadAllBytes(Ruta);

            using (ZipFile zip = new ZipFile())
            {
                zip.AddDirectory(Ruta);

                using (MemoryStream output = new MemoryStream())
                {
                    zip.Save(output);
                    return File(output.ToArray(), "application/zip", NombreCarpeta+".zip");
                }
            }

        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging; 
using System.Diagnostics; 
using ClientesProspectos.Models;
using System.Collections.Generic;
using System;
using System.IO;

namespace ClientesProspectos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Login()
        {

            HttpContext.Session.SetString("Usuario", "");
            ViewBag.sessionv = "";

            return View();

        }

        public IActionResult Inicio()
        {
            ViewBag.sessionv = HttpContext.Session.GetString("Usuario");
            if (ViewBag.sessionv != "")
            {

                ViewData["Usuario"] = ViewBag.sessionv;

                return View();
            }
            else
            {
                return RedirectToPage("/");
            }
        }

        public IActionResult Listado()
        {
            ViewBag.sessionv = HttpContext.Session.GetString("Usuario");
            if (ViewBag.sessionv != "")
            {

                ViewData["Usuario"] = ViewBag.sessionv;

                return View();
            }
            else
            {
                return RedirectToPage("/");
            }
        }

        public IActionResult Captura()
        {
            ViewBag.sessionv = HttpContext.Session.GetString("Usuario");
            if (ViewBag.sessionv != "")
            {

                ViewData["Usuario"] = ViewBag.sessionv;

                return View();
            }
            else
            {
                return RedirectToPage("/");
            }
        }

        public IActionResult Evaluacion()
        {
            ViewBag.sessionv = HttpContext.Session.GetString("Usuario");
            if (ViewBag.sessionv != "")
            {

                ViewData["Usuario"] = ViewBag.sessionv;

                return View();
            }
            else
            {
                return RedirectToPage("/");
            }
        }

        public IActionResult Index()
        {
            ViewBag.sessionv = HttpContext.Session.GetString("Usuario");
            if (ViewBag.sessionv != "")
            {

                ViewData["Usuario"] = ViewBag.sessionv;

                return View();
            }
            else
            {
                return RedirectToPage("/");
            }
        }
    }
}

Views/Home/Captura.cshtml
@{
    ViewData["Title"] = "App ClientesProspectos";
} 
@Html.AntiForgeryToken()

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">  
    <link href="~/css/Capturar.css" rel="stylesheet" />
    <title>Directorio Telefonico</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="https://code.jquery.com/jquery-1.10.2.js" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.7/dist/sweetalert2.all.min.js" integrity="sha256-oRlny88mMfxoVA0EAcCwBibDn14Ui/A9Wc8903cpHMk=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.7/dist/sweetalert2.all.min.js" integrity="sha256-oRlny88mMfxoVA0EAcCwBibDn14Ui/A9Wc8903cpHMk=" crossorigin="anonymous"></script>

    <link href="~/Scripts/dropzone.min.css" rel="stylesheet" />
    <script src="~/Scripts/dropzone.min.js"></script>

</head>
<body style="background-color: silver;">

    <input id="ideus" value="@ViewData["Usuario"]" style="display:none;" disabled="disabled" />

    <script>
        var ideus = document.getElementById('ideus')
        if (ideus.value == "" || ideus.value == null) { 
        window.location.href = "/"
        }
    </script>

    <div id="ElLoader" class="preloader" style="display:none;">
        <img style=" width: 100%;" src="~/img/Loader.png" alt="">
    </div>

    @*MODAL*@
    <!-- Button trigger modal -->
    <button id="btnCapturarArchivos" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" style="display:none; margin:10px; background-color:gray; border: solid 1px gray;">Adjuntar archivos</button>


    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
           
            <form method="post" enctype="multipart/form-data" asp-controller="Archivos" asp-action="FileUpload">
                <div class="form-group"> 
                    <div style="display:flex; flex-direction: row;">
                        <div class="col" style="display:flex; flex-direction:column; justify-content:center; align-items: center; width:50%; border:dotted 2px green; border-radius: 10px; ">
                            <p>Click para buscar docs.</p>                            
                            <label class="btn btn-default btn-sm center-block btn-file">
                              <i class="fa fa-upload fa-2x" aria-hidden="true"></i>              
                              <input type="file" name="files" multiple style="display: none;"/>
                            </label>                        
                            <input name="usuario" id="IdProspectoCarpeta" style="display:none;"/>
                        </div>
                        <div style="display:flex; justify-content:center; align-items: center; width:50%;">
                            <input type="submit" value="Subir" class="btn btn-primary" style="background-color:green; border: solid 1px green; height:40px; "/>
                        </div>
                    </div>
                </div>

                <div>
                    <div class="col"> 
                        @*<input type="submit" value="Subir" class="btn btn-primary" style="background-color:green; border: solid 1px green;"/>*@
                    </div>
                </div>
            </form>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">No Subir</button>
          </div>
        </div>
      </div>
    </div>
    @*MODAl*@

    <div style="display:flex; width:100%; height:10vh; justify-content:center;">
        <div class="tab-content" style="display:flex; flex-direction:row; align-items: center; justify-content:center;  margin-top:22px; background-color:green;">
            <h2 class="TituloH2">Capturar</h2>
        </div>
    </div>

    <div class="tab-content" style="margin-top:22px; background-color:#f8f9fa;" id="VistaBlanca">

        <div  style="width:100%; ">
            <div class="animate__animated animate__headShake">
                <div style="display:flex; flex-direction:column;">
                    <div class="ContenedorInputs">
                        <input class="form-control" style="margin:10px;" placeholder="Nombre" maxlength="100" id="txtNombre"/>
                        <input class="form-control" style="margin:10px;" placeholder="APaterno" maxlength="50" id="txtAPaterno"/>
                        <input class="form-control" style="margin:10px;" placeholder="AMaterno" maxlength="50" id="txtAMaterno"/>
                    </div>
                    <div class="ContenedorInputs">
                        <input class="form-control" style="margin:10px;" placeholder="Calle" maxlength="100" id="txtCalle"/>
                        <input class="form-control" style="margin:10px;" placeholder="Numero" type="number" min="1" max="9999" id="txtNumero"/>
                        <input class="form-control" style="margin:10px;" placeholder="Colonia" maxlength="100" id="txtColonia"/>
                    </div>
                    <div class="ContenedorInputs">
                        <input class="form-control" style="margin:10px;" placeholder="CP" type="number" min="1" max="99999" id="txtCP"/>
                        <input class="form-control" style="margin:10px;" placeholder="Teléfono" type="number" min="1" max="999999999999" id="txtTelefono"/>
                        <input class="form-control" style="margin:10px;" placeholder="RFC" maxlength="13" id="txtRFC"/>
                    </div>
                    <div style="display:flex; flex-direction:row;">
                        <div style="display:flex; justify-content:flex-start; width:50%;">
                            <button class="btn btn-primary" style="margin:10px; background-color:red; border: solid 1px red;" id="btnSalir">Salir</button>
                        </div>
                        <div style="display:flex; justify-content:flex-end; width:50%;">
                            <button class="btn btn-primary" style="margin:10px; background-color:green; border: solid 1px green;" id="btnCapturar">Capturar</button>
                        </div>                            
                    </div> 
                </div>
            </div>
        </div>                  
    </div>

    <div class="tab-content" style="height:10vh; margin-top:22px; margin-bottom:22px;">
        <button class="btn btn-primary" style="background-color:green; border-color:green; margin-top:-10px;" onclick="location.href='/Home/Login'">Cerrar Sesion</button>
    </div>

    <script src="~/js/Captura.js"></script>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.7/dist/sweetalert2.all.min.js" integrity="sha256-oRlny88mMfxoVA0EAcCwBibDn14Ui/A9Wc8903cpHMk=" crossorigin="anonymous"></script>

</body>
</html>

Views/Home/Evaluacion.cshtml
@{
    ViewData["Title"] = "App ClientesProspectos";
}
@Html.AntiForgeryToken();

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="~/css/Evaluacion.css" rel="stylesheet" />
    <title>Directorio Telefonico</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="https://code.jquery.com/jquery-1.10.2.js" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.7/dist/sweetalert2.all.min.js" integrity="sha256-oRlny88mMfxoVA0EAcCwBibDn14Ui/A9Wc8903cpHMk=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.7/dist/sweetalert2.all.min.js" integrity="sha256-oRlny88mMfxoVA0EAcCwBibDn14Ui/A9Wc8903cpHMk=" crossorigin="anonymous"></script>

</head>
<body style="background-color: silver;">

    <input id="ideus" value="@ViewData["Usuario"]" style="display:none;" disabled="disabled" />

    <script>
        var ideus = document.getElementById('ideus')
        if (ideus.value == "" || ideus.value == null) {
        window.location.href = "/"
        }
    </script>

    <div id="ElLoader" class="preloader" style="display:none;">
        <img style=" width: 100%;" src="~/img/Loader.png" alt="">
    </div>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" id="btnAbrirModal" style="display:none;">
        Launch demo modal
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Detalle Prospecto</h5>
                </div>
                <div class="modal-body">
                    <div class="ContenedorInputs">
                        <div class="col" style="display:flex; flex-direction:column; margin-top:10px;">
                            <label class="form-text">ID</label>
                            <input id="txtIdProspecto" disabled="disabled" style="width:100px;" class="form-control" /> 
                        </div>

                        <form method="post" enctype="multipart/form-data" asp-controller="Archivos" asp-action="FileDownload">
                            <div class="form-group"> 
                                <div style="display:flex; flex-direction: row;">
                                    <div class="col" style="display:flex; flex-direction:column; justify-content:center; align-items: center; width:50%; ">              
                                        <input name="usuario" id="txtIDArchivo" style="display:none;"/>
                                    </div>
                                    <div style="display:flex; justify-content:center; align-items: center;">
                                        <input type="submit" value="DescargarArchivos" class="btn btn-primary" style="background-color:green; border: solid 1px green; height:40px; "/>
                                    </div>
                                </div>
                            </div>
                        </form>

                    </div>
                    <div class="ContenedorInputs">
                        <div class="col" style="display:flex; flex-direction:column; margin-top:10px;">
                            <label class="form-text">Nombre</label>
                            <input class="form-control" disabled="disabled" id="txtNombre" />
                        </div>
                        <div class="col" style="display:flex; flex-direction:column; margin-top:10px;">
                            <label class="form-text">Apellido Paterno</label>
                            <input class="form-control" disabled="disabled" id="txtAPaterno" />
                        </div>
                        <div class="col" style="display:flex; flex-direction:column; margin-top:10px;">
                            <label class="form-text">Apellido Materno</label>
                            <input class="form-control" disabled="disabled" id="txtAMaterno" />
                        </div>
                    </div>
                    <div class="ContenedorInputs">
                        <div class="col" style="display:flex; flex-direction:column; margin-top:10px;">
                            <label class="form-text">Calle</label>
                            <input class="form-control" disabled="disabled" id="txtCalle" />
                        </div>
                        <div class="col" style="display:flex; flex-direction:column; margin-top:10px;">
                            <label class="form-text">Numero</label>
                            <input class="form-control" disabled="disabled" id="txtNumero" />
                        </div>
                        <div class="col" style="display:flex; flex-direction:column; margin-top:10px;">
                            <label class="form-text">Colonia</label>
                            <input class="form-control" disabled="disabled" id="txtColonia" />
                        </div>
                    </div>
                    <div class="ContenedorInputs">
                        <div class="col" style="display:flex; flex-direction:column; margin-top:10px;">
                            <label class="form-text">CP</label>
                            <input class="form-control" disabled="disabled" id="txtCP" />
                        </div>
                        <div class="col" style="display:flex; flex-direction:column; margin-top:10px;">
                            <label class="form-text">Telefono</label>
                            <input class="form-control" disabled="disabled" id="txtTelefono" />
                        </div>
                        <div class="col" style="display:flex; flex-direction:column; margin-top:10px;">
                            <label class="form-text">RFC</label>
                            <input class="form-control" disabled="disabled" id="txtRFC" />
                        </div>
                    </div>
                    <div class="ContenedorSelect" style="margin-top:20px;">
                        <div class="form-floating" style="width:200px;">
                            <select class="form-select" id="SelectStatus" aria-label="Floating label select example">
                                <option value="Autorizado">Autorizado</option>
                                <option value="Rechazado">Rechazado</option> 
                            </select>
                            <label for="floatingSelect">Actualizar Status</label>
                        </div>
                    </div>
                    <div class="col" id="ContenedorObservaciones" style="display:none; flex-direction:column;">
                        <label class="form-text">Observaciones</label>
                        <textarea id="txtObservaciones" class="form-text"></textarea>
                    </div>
                    <button class="btn btn-primary" id="btnActualizar" style="height:40px; margin:10px; background-color:green; border: solid 1px green;">Actualizar</button>

                    <button id="btnLlenarModal" style="display:none;">b</button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

    <div style="display:flex; width:100%; height:10vh; justify-content:center;">
        <div class="tab-content" style="display:flex; flex-direction:row; align-items: center; justify-content:center;  margin-top:22px; background-color:green;">
            <h2 class="TituloH2">Evaluar</h2>
        </div>
    </div>

    <div class="tab-content" style="margin-top:22px; background-color:#f8f9fa;" id="VistaBlanca">

        <div style=" width:100%;">
            <div class="album py-3 bg-light">
                <div class="container">
                    <div class="animate__animated animate__headShake">
                        <div style="display:flex; flex-direction:row;">
                            <div style="display:flex; justify-content:flex-start; width:50%;">
                                <img src="~/img/regresar.png" style="height:30px; cursor:pointer; margin-bottom:20px; " onclick="location.href='/Home/Inicio'" />
                            </div>
                        </div>
                        <div>
                            <table class="table" id="TablaProspectos">
                                <thead>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="tab-content" style="display:flex; justify-content:center; height:10vh; margin-top:22px; margin-bottom:22px;">
        <button class="btn btn-primary" style="background-color:green; border-color:green; margin-top:13px; height:40px;" onclick="location.href='/Home/Login'">Cerrar Sesion</button>
    </div>

    <script src="~/js/Evaluacion.js"></script>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.7/dist/sweetalert2.all.min.js" integrity="sha256-oRlny88mMfxoVA0EAcCwBibDn14Ui/A9Wc8903cpHMk=" crossorigin="anonymous"></script>

</body>
</html>

Views/Home/Index.cshtml
@*        <form method="post" enctype="multipart/form-data" asp-controller="Archivos" asp-action="Index">
            <div class="form-group"> 
                <div class="col">
                    <p>Subir archivos</p>
                    <input type="file" name="files" multiple/>
                    <input name="usuario" placeholder="NombreCarpetaNueva"/>
                </div>
            </div>
            <div>
                <div class="col"> 
                    <input type="submit"/>
                </div>
            </div>
        </form>*@

Views/Home/Inicio.cshtml
@{
    ViewData["Title"] = "App ClientesProspectos";
} 
@Html.AntiForgeryToken()

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">  
    <link href="~/css/Inicio.css" rel="stylesheet" />
    <title>Directorio Telefonico</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="https://code.jquery.com/jquery-1.10.2.js" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.7/dist/sweetalert2.all.min.js" integrity="sha256-oRlny88mMfxoVA0EAcCwBibDn14Ui/A9Wc8903cpHMk=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.7/dist/sweetalert2.all.min.js" integrity="sha256-oRlny88mMfxoVA0EAcCwBibDn14Ui/A9Wc8903cpHMk=" crossorigin="anonymous"></script>

</head>
<body style="background-color: silver;">

    <input id="ideus" value="@ViewData["Usuario"]" style="display:none;" disabled="disabled" />

    <script>
        var ideus = document.getElementById('ideus')
        if (ideus.value == "" || ideus.value == null) { 
        window.location.href = "/"
        }
    </script>

    <div id="ElLoader" class="preloader" style="display:none;">
        <img style=" width: 100%;" src="~/img/Loader.png" alt="">
    </div>

    <div style="display:flex; width:100%; height:10vh; justify-content:center;">
        <div class="tab-content" style="display:flex; flex-direction:row; align-items: center; justify-content:center;  margin-top:22px; background-color:green;">
            <h2 class="TituloH2">Clientes Prospectos</h2>
        </div>
    </div>

    <div class="tab-content" style="margin-top:22px; background-color:#f8f9fa;" id="VistaBlanca">

        <div  style=" width:100%; background-color:red; margin-top:100px; margin-bottom:100px;">
            <div class="album py-3 bg-light">
                <div class="container">
                    <div class="animate__animated animate__headShake">
                        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" style="justify-content:center;">
           
                            @*<li><button class="dropdown-item" id="btnEdoCuenta">Estado de Cuenta</button></li>   *@
                            <button class="btn btn-primary" style="margin:auto; margin-bottom:30px; border-radius:20px; width:200px; height:200px; border-color:green; background-color:green; border-color:transparent;" onclick="location.href='/Home/Listado'"> LISTADO DE PROSPECTOS </button>

                            @*<li><button class="dropdown-item" id="btnSaldos" >Saldos</button></li>*@
                            <button class="btn btn-primary" style="margin:auto; margin-bottom:30px; border-radius:20px; width:200px; height:200px; border-color:green; background-color:green; border-color:transparent;" onclick="location.href='/Home/Captura'"> CAPTURA DE PROSPECTO </button>
                            
                            @*<li><button class="dropdown-item" id="btnAutorizacionesPedidos">Autorizaciones Pedidos</button></li>*@
                            <button class="btn btn-primary" style="margin:auto; margin-bottom:30px; border-radius:20px; width:200px; height:200px; border-color:green; background-color:green; border-color:transparent;" onclick="location.href='/Home/Evaluacion'"> EVALUACIÓN DEL PROSPECTO</button>

                        </div>
                    </div> 
                </div>
            </div>
        </div>                

    </div>

    <div class="tab-content" style="height:10vh; margin-top:22px; margin-bottom:22px;">
        <button class="btn btn-primary" style="background-color:green; border-color:green; margin-top:-10px;" onclick="location.href='/Home/Login'">Cerrar Sesion</button>
    </div>

    <script src="~/js/Inicio.js"></script>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.7/dist/sweetalert2.all.min.js" integrity="sha256-oRlny88mMfxoVA0EAcCwBibDn14Ui/A9Wc8903cpHMk=" crossorigin="anonymous"></script>

</body>
</html>